### ISSUE TITLE
Missing compiler header "set" when built on ARM64 Windows WSL in AuxData.hpp

### ISSUE THREAD

**Issue by PhiliaTheCat** [GrammaTech/gtirb#68]
When built on ARM64 Windows WSL, some files including AuxData.hpp do not compile because compiler can't see the symbol "std::set".

**Comment by jdorn-gt** [comment]
Could you provide some more details, such as the distro you're running in WSL, what compiler you're using, what commands you're running to build GTIRB, and the exact error message you're seeing? Unfortunately, I do not have an ARM64 Windows system available to test on, so I will need your help to understand the issue.

It is surprising that the compiler would not be able to see `std::set` while compiling AuxData.hpp, since that header explicitly includes `<set>`: https://github.com/GrammaTech/gtirb/blob/b94487994ca7ad046aa78c39d073ec2027bc38a6/include/gtirb/AuxData.hpp#L26 This makes me wonder if the issue might be something in your environment.

**Comment by PhiliaTheCat** [comment]
It seems to be my fault that I was using the src tree of v2.1.0. But there is still something wrong afterward. I will open another issue for that, and close this one.
